### PR TITLE
#228 issue: fix report maker

### PR DESCRIPTION
**Pull request by ke4**
The list of code fixes:
Fix a null issue in the 'run' method.
Passing an array of URIs instead of IDs to artefacts batch request.
Fixing the issue if a sample has been run more than once through a step producing an UDF field.
Fixing the problem to build the details of the artefacts.
Added correct test data.

### CODE REVIEW

**Comment by jbeast** [comment]
Are there some docs you can point me to?

**Comment by ke4** [comment]
What do you mean by docs? I just fixed obvious bugs what I listed in the comment section of the PR.

**Comment by jbeast** [comment]
At the retrospective, we agreed that we'd start adhering to what was on the "definition of done", in that documentation is needed for things to be "done".

**Comment by ke4** [comment]
Yes, but it is not for bug fixing. It is for documenting a feature.
As I wrote I just fixed obvious bugs like passing URIs and not IDs when an API call is waiting for URIs, but not for plain IDs.
Please, check my PR.

**Pull request merged**
